import tiktoken

# Laad het model voor text-embedding-ada-002
tokenizer = tiktoken.get_encoding("cl100k_base")

# Voorbeeldtekst
text = "Het is van groot belang dat de juiste brandstof wordt getankt. Indien de werkelijke brandstofkosten\nmeer dan 20% afwijken van de door de leasemaatschappij gehanteerde norm, worden de\nmeerkosten aan je doorbelast.\nGebruik tankpas\nDe ter beschikking gestelde tankpas en pincode zijn betaalmiddelen voor brandstof, olie- en\nsmeermiddelen en ruitenvloeistof in Nederland. Ze vertegenwoordigen dus geld. De tankpas en de\nbijbehorende pincode dienen dan ook separaat te worden bewaard en overeenkomstig de\ninstructies van de leverancier te worden gebruikt. Het risico van verlies en diefstal respectievelijk de\nkosten en schade voortvloeiend uit misbruik van de aan jou verstrekte tankpas zijn voor eigen\nrekening.\nHet is niet toegestaan andere producten dan brandstof, olie- en smeermiddelen en ruitenvloeistof\nmet de tankpas aan te schaffen. Evenmin is het niet toegestaan brandstof en/of smeermiddelen te\nbetalen voor een andere auto dan de door Digital Power aan jou ter beschikking gestelde leaseauto.\nBrandstofbetaling voorgeschoten\nHet kan gebeuren dat je de brandstofkosten op een andere manier hebt moeten afrekenen dan met\nde aan jou verstrekte tankpas. De brandstofkosten die je hebt voorgeschoten kun je declareren via\nde salarisadministratie van Digital Power. Zie voor meer informatie over declareren hoofdstuk 6 van\nhet Digital Talent Handboek.\nTanken en invoeren kilometerstand\nBij het tanken van de leaseauto is het verplicht om na het invoeren van de pincode ook de juiste\nkilometerstand in te voeren.\nProcedure bij schade of verlies\nBij verlies of diefstal van de tankpas dien je de leasemaatschappij direct telefonisch in kennis te\nstellen en dit binnen 48 uur schriftelijk of per e-mail te bevestigen. Het is uitermate belangrijk dat de"
text_small = "Het is van groot belang dat de juiste brandstof wordt getankt. Indien de werkelijke brandstofkosten\nmeer dan 20% afwijken van de door de leasemaatschappij gehanteerde norm, worden de\nmeerkosten aan je doorbelast.\nGebruik tankpas\nDe ter beschikking gestelde tankpas en pincode zijn betaalmiddelen voor brandstof, olie- en\nsmeermiddelen en ruitenvloeistof in Nederland. Ze vertegenwoordigen dus geld. De tankpas en de\nbijbehorende pincode dienen dan ook separaat te worden bewaard en overeenkomstig de\ninstructies van de leverancier te worden gebruikt. Het risico van verlies en diefstal respectievelijk de\nkosten en schade voortvloeiend uit misbruik van de aan jou verstrekte tankpas zijn voor eigen\nrekening.\nHet is niet toegestaan andere producten dan brandstof, olie- en smeermiddelen en ruitenvloeistof\nmet de tankpas aan te schaffen. Evenmin is het niet toegestaan brandstof en/of smeermiddelen te\nbetalen voor een andere auto dan de door Digital Power aan jou ter beschikking gestelde leaseauto.\nBrandstofbetaling voorgeschoten\nHet kan gebeuren dat je de brandstofkosten op een andere manier hebt moeten afrekenen dan met"
# Tel het aantal tokens
tokens = tokenizer.encode(text_small)
print(len(tokens))  # Geeft het aantal tokens terug